---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: dgodd/cf-cli
inputs:
- name: cf-space
- name: samples
run:
  path: sh
  args:
  - -exc
  - |
    ./cf-space/login
    . ./cf-space/variables

    export SAFESPACE=`echo $SPACE | sed 's/_/-/g' | sed 's/^test-//g'`

    cf target -s shoetree-system
    cf map-route whale-db cfapps.pez.pivotal.io --hostname whale-db-${SAFESPACE}

    cf target -s $SPACE

    set +x
    echo "cf create-service-broker WhaleDB${SAFESPACE} admin [ADMIN_PASSWORD] https://whale-db-${SAFESPACE}.cfapps.pez.pivotal.io --space-scoped"
    cf create-service-broker WhaleDB${SAFESPACE} admin ${ADMIN_PASSWORD} https://whale-db-${SAFESPACE}.cfapps.pez.pivotal.io --space-scoped
