---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: dgodd/dotnet
inputs:
- name: cf-space
- name: samples
run:
  path: sh
  args:
  - -exc
  - |
    ./cf-space/login
    export SPACE=`cat cf-space/name`
    if [ ! -z "$CREATE_SERVICE" ]; then
      cf create-service $CREATE_SERVICE
    fi
    if [ ! -z "$CREATE_CUPS" ]; then
      export CREATE_CUPS=$(echo $CREATE_CUPS | sed "s/\${SPACE}/$SPACE/")
      cf cups $CREATE_CUPS
    fi
