---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: dgodd/dotnet
inputs:
- name: cf-space
- name: samples
run:
  path: sh
  args:
  - -exc
  - |
    ./cf-space/login
    export SPACE=`cat cf-space/name`
    if [ ! -z "$CREATE_SERVICE" ]; then
      cf create-service $CREATE_SERVICE
    fi
    if [ ! -z "$CREATE_CUPS" ]; then
      cf cups $(echo $CREATE_CUPS | sed "s/\${SPACE}/$SPACE/g")
    fi

    set +x
    while [ `cf services | grep 'in progress' | wc -l | sed 's/ //g'` != 0 ]; do
      echo 'Waiting for services to start'
      cf services | grep 'in progress'
      echo
      sleep 5
    done

    if [ `cf services | grep 'create failed' | wc -l | sed 's/ //g'` > 0 ]; do
      echo 'Some services failed to start'
      cf services
      echo
      exit 1
    fi
