---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: dgodd/dotnet
inputs:
- name: samples
outputs:
- name: publish
run:
  path: sh
  args:
  - -exc
  - |
    export PUBLISH_DIR=$PWD/publish
    cd $SOURCE_DIR
    cp $MANIFEST_YAML $PUBLISH_DIR/manifest.yml
    dotnet restore
    dotnet publish --output $PUBLISH_DIR --configuration Release --framework $FRAMEWORK --runtime $RUNTIME
