---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: dgodd/ruby
inputs:
- name: cf-space
outputs:
- name: cf-app-login
run:
  path: sh
  args:
  - -euxc
  - |
    curl -L 'https://cli.run.pivotal.io/stable?release=linux64-binary&source=github' | tar -zx -C /usr/local/bin/
    ./cf-space/login
    . ./cf-space/variables

    uaac target https://myuaa-${SPACE}.cfapps.pez.pivotal.io
    uaac token client get admin -s adminsecret
    uaac contexts
    uaac group add testgroup || true
    uaac user add user${SPACE} --given_name Integration --family_name Test --emails test@testcloud.com --password Password1!
    uaac member add testgroup user${SPACE}
    uaac client add ${SPACE}TestApp --name ${SPACE}TestApp --scope cloud_controller.read,cloud_controller_service_permissions.read,openid,testgroup --authorized_grant_types authorization_code,refresh_token --authorities uaa.resource --redirect_uri http://single-signon-${SPACE}.cfapps.pez.pivotal.io/signin-cloudfoundry --autoapprove cloud_controller.read,cloud_controller_service_permissions.read,openid,testgroup --secret ${SPACE}TestApp
    echo "{\"username\":\"user${SPACE}\",\"password\":\"Password1!\"}" > cf-app-login/login.json
