---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: dgodd/ruby
inputs:
- name: cf-space
outputs:
- name: cf-app-login
run:
  path: sh
  args:
  - -euxc
  - |
    curl -L 'https://cli.run.pivotal.io/stable?release=linux64-binary&source=github' | tar -zx -C /usr/local/bin/
    ./cf-space/login
    . ./cf-space/variables
    uaac target uaa.pcfdev.shoetree.io --skip-ssl-validation
    uaac token client get admin -s admin-client-secret
    uaac contexts
    uaac user delete user${SPACE}
