---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: dgodd/ruby
inputs:
- name: steeltoe-ci
- name: cf-space
run:
  path: sh
  args:
  - -euxc
  - |
    export SPACE=`cat cf-space/name`
    ./steeltoe-ci/scripts/test-$FILENAME.rb
