---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: steeltoeoss/cf-cli
inputs:
- name: cf-space
- name: samples
run:
  path: sh
  args:
  - -exc
  - |
    ./cf-space/login || true
    . ./cf-space/variables

    cf target -s shoetree-system
    cf unmap-route whale-db cfapps.pez.pivotal.io --hostname whale-db-${SPACE}
