---
resource_types:
- name: cf-space-resource
  type: docker-image
  source:
    repository: dgodd/cf-space-resource

resources:
- name: steeltoe-ci
  type: git
  source:
    uri: https://github.com/SteelToeOSS/steeltoe-ci.git
    branch: master
- name: samples
  type: git
  source:
    uri: https://github.com/SteelToeOSS/Samples.git
    branch: dev
- name: connectors
  type: git
  source:
    uri: https://github.com/SteelToeOSS/Connectors.git
    branch: dev
- name: cf-space
  type: cf-space-resource
  source:
    target: {{cf_target}}
    username: {{cf_username}}
    password: {{cf_password}}
    organization: integration

jobs:
- name: postgres-efcore-linux
- name: cleanup
  plan:
  - task: remove-all-spaces
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: dgodd/cf-cli
      params:
        CF_TARGET: {{cf_target}}
        CF_USERNAME: {{cf_username}}
        CF_PASSWORD: {{cf_password}}
        CF_ORGANIZATION: integration
      run:
        path: sh
        args:
        - -exc
        - |
          echo | cf login -a $CF_TARGET -u $CF_USERNAME -p $CF_PASSWORD --skip-ssl-validation -o integration
          cf curl "/v2/organizations?q=name%3A${CF_ORGANIZATION}&inline-relations-depth=1" | jq -r '.resources[0].entity.spaces|sort_by(.metadata.created_at)|reverse|.[].entity.name' | xargs -n1 cf delete-space -f

  plan:
  - get: steeltoe-ci
  - get: connectors
    trigger: true
  - get: samples
    path: Connectors/src/PostgreEFCore/
    trigger: true
  - put: cf-space
  - task: push-app
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: dgodd/cf-cli
      inputs:
      - name: cf-space
      - name: samples
      run:
        path: sh
        args:
        - -exc
        - |
          ./cf-space/login
          cd samples/Connectors/src/PostgreEFCore/
          cf create-service WhaleDB public myPostgres
          cf push -f manifest-linux.yml
  - task: test-app
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: dgodd/cf-cli
      inputs:
      - name: cf-space
      run:
        path: bash
        args:
        - -exc
        - |
          ./cf-space/login
          export URL=`cf app postgres-connector | grep '^urls: ' | cut -d ' ' -f 2`
          if [[ `curl -k https://$URL/Home/PostgresData` == *"<h3>Key2="* ]]; then
            echo "Found Key2"
          else
            exit 1
          fi
  - task: delete-space
    file: steeltoe-ci/tasks/delete-space.yml

- name: rabbit-linux
  plan:
  - get: steeltoe-ci
  - get: connectors
    trigger: true
  - get: samples
    path: Connectors/src/Rabbit/
    trigger: true
  - put: cf-space
  - task: push-app
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: dgodd/cf-cli
      inputs:
      - name: cf-space
      - name: samples
      run:
        path: sh
        args:
        - -exc
        - |
          ./cf-space/login
          cd samples/Connectors/src/Rabbit/
          cf create-service p-rabbitmq standard myRabbitService
          cf push -f manifest.yml
  - task: test-app
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: dgodd/cf-cli
      inputs:
      - name: cf-space
      run:
        path: bash
        args:
        - -exc
        - |
          ./cf-space/login
          export URL=`cf app rabbit-demo | grep '^urls: ' | cut -d ' ' -f 2`
          if [[ `curl -k https://$URL/` == *"<h3>Message="* ]]; then
            echo "Found Message"
          else
            exit 1
          fi
  - task: delete-space
    file: steeltoe-ci/tasks/delete-space.yml
